name: Unit Test Workflow

on:
  push:         # El trigger que dispara, en este caso, un push
    branches:
      - main    # Las ramas donde se ejecutará este workflow

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      TEST_ENV: true
    steps:
      - name: Configurar repositorio
        uses: actions/checkout@v3
      
      - name: Instalar dependencias
        run: |
          cd backend  # Cambiar al directorio de la aplicación
          pip install -r requirements.txt
      
      - name: Ejecutar pruebas y generar cobertura
        run: |
          cd backend  # Cambiar al directorio de la aplicación
          TEST_ENV=true pytest --cov=app --cov-report=xml  # Generar reporte de cobertura en formato XML
          
      - name: Subir cobertura a Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/coverage.xml  # Ruta al archivo XML de cobertura generado
          token: ${{ secrets.CODECOV_TOKEN }}
